In [263]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

import pickle




In [264]:
#mass = pd.read_csv('../data/03_mass_no_country.csv')

In [265]:
X = pd.read_csv('../data/x_sample.csv')

In [266]:
X.head()

protestnumber  protesterviolence   pop_total  pop_density  prosperity_2020  \
0              1                0.0   73030.879      244.930        56.900724   
1              2                1.0    3862.998       71.024        44.029639   
2              1                0.0  927403.866      311.922        53.640353   
3             14                0.0    4058.131       58.907        80.176044   

   region_Africa  region_Asia  region_Central America  region_Europe  \
0              0            1                       0              0   
1              1            0                       0              0   
2              0            1                       0              0   
3              0            0                       0              1   

   region_MENA  ...  protester_id_type_victims_families  \
0            0  ...                                   0   
1            0  ...                                   0   
2            0  ...                                   0   
3            0  ...                                   0   

   protester_id_type_women  protester_id_type_workers_unions  \
0                        0                                 0   
1                        0                                 0   
2                        0                                 0   
3                        0                                 0   

   labor_wage_dispute  land_farm_issue  police_brutality  \
0                   0                0                 0   
1                   0                0                 0   
2                   0                0                 0   
3                   0                0                 0   

   political_behavior_process  price increases_tax_policy  \
0                           1                           0   
1                           1                           0   
2                           1                           0   
3                           1                           0   

   removal_of_politician  social_restrictions  
0                      0                    0  
1                      0                    0  
2                      0                    0  
3                      0                    0  

[4 rows x 40 columns]

#### Load model from pickle file

In [267]:
# load the model from disk
model_file = '../models/01_multi_label_forest.pickle'
loaded_model = pickle.load(open(model_file, 'rb'))




In [268]:
result = loaded_model.predict(X)

print(result)

[[0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0]]


First, delete all rows from X that were the four rows of test data.

In [269]:
X.drop([0,1,2,3], inplace=True)  # drop the four rows of old data.

### Create input records for a few protests in the United States.


#### 1999 Seattle World Trade Organization protest

[1999 Seattle World Trade Organization protest](https://en.wikipedia.org/wiki/1999_Seattle_WTO_protests)


Create a row for each protest.

In [270]:
# 1999 Seattle
# Create a dictionary that contains a value for each of the 40 input features

new_protest = {
    'protestnumber': 1,
    'protesterviolence': 1,
    'pop_total': 278548.148,  # Taken from WPP2019_TotalPopulationBySex.csv
    'pop_density':30.45,
    'prosperity_2020': 77.5,  # Taken from Legatum_Prosperity_Index_Full_2020_Data_Set Excel file - Score from 2007
    'region_Africa': 0,
    'region_Asia': 0,
    'region_Central America': 0,
    'region_Europe': 0,
    'region_MENA': 0,
    'region_North America': 1,
    'region_Oceania': 0,
    'region_South America': 0,
    'protest_size_category_1,000-4,999': 0,
    'protest_size_category_10,000-100,000': 1,   #Protest size around 50,000 or more
    'protest_size_category_100-999': 0,
    'protest_size_category_5,000-9,999': 0,
    'protest_size_category_50-99':0 ,
    'protest_size_category_Less than 50': 0,
    'protest_size_category_Over 100,000': 0,
    'protester_id_type_civil_human_rights': 0,
    'protester_id_type_ethnic_group': 0,
    'protester_id_type_locals_residents': 0,
    'protester_id_type_pensioners_retirees': 0,
    'protester_id_type_political_group': 0,
    'protester_id_type_prisoners': 0,
    'protester_id_type_protestors_generic': 0,
    'protester_id_type_religious_group': 0,
    'protester_id_type_soldiers_veterans': 0,
    'protester_id_type_students_youth':0,
    'protester_id_type_victims_families': 0,
    'protester_id_type_women':0,
    'protester_id_type_workers_unions': 1,
    'labor_wage_dispute': 1,
    'land_farm_issue': 0,
    'police_brutality':0,
    'political_behavior_process': 1,
    'price increases_tax_policy': 1,
    'removal_of_politician':0,
    'social_restrictions':1
}
        
X.loc["1999 Seattle WTO Protest"] = new_protest
X

protestnumber  protesterviolence   pop_total  \
1999 Seattle WTO Protest            1.0                1.0  278548.148   

                          pop_density  prosperity_2020  region_Africa  \
1999 Seattle WTO Protest        30.45             77.5            0.0   

                          region_Asia  region_Central America  region_Europe  \
1999 Seattle WTO Protest          0.0                     0.0            0.0   

                          region_MENA  ...  \
1999 Seattle WTO Protest          0.0  ...   

                          protester_id_type_victims_families  \
1999 Seattle WTO Protest                                 0.0   

                          protester_id_type_women  \
1999 Seattle WTO Protest                      0.0   

                          protester_id_type_workers_unions  \
1999 Seattle WTO Protest                               1.0   

                          labor_wage_dispute  land_farm_issue  \
1999 Seattle WTO Protest                 1.0              0.0   

                          police_brutality  political_behavior_process  \
1999 Seattle WTO Protest               0.0                         1.0   

                          price increases_tax_policy  removal_of_politician  \
1999 Seattle WTO Protest                         1.0                    0.0   

                          social_restrictions  
1999 Seattle WTO Protest                  1.0  

[1 rows x 40 columns]

#### March for Our Lives Protest
This took place in March, 2018.

The [March for Our Lives (MFOL)](https://en.wikipedia.org/wiki/March_for_Our_Lives) is a student-led demonstration in support of gun control legislation.


In [271]:
# March, 2018 - March for Our Lives Protest
# Create a dictionary that contains a value for each of the 40 input features

new_protest = {
    'protestnumber': 4,  # Random guess
    'protesterviolence': 0,
    'pop_total': 327096.263,  # Taken from WPP2019_TotalPopulationBySex.csv
    'pop_density':35.76,
    'prosperity_2020': 77.5,  # Taken from Legatum_Prosperity_Index_Full_2020_Data_Set Excel file - Score from 2007
    'region_Africa': 0,
    'region_Asia': 0,
    'region_Central America': 0,
    'region_Europe': 0,
    'region_MENA': 0,
    'region_North America': 1,
    'region_Oceania': 0,
    'region_South America': 0,
    'protest_size_category_1,000-4,999': 0,  
    'protest_size_category_10,000-100,000': 0,   
    'protest_size_category_100-999': 0,
    'protest_size_category_5,000-9,999': 0,
    'protest_size_category_50-99':0 ,
    'protest_size_category_Less than 50': 0,
    'protest_size_category_Over 100,000': 1,  #Protest nation-wide, over 1 million
    'protester_id_type_civil_human_rights': 0,
    'protester_id_type_ethnic_group': 0,
    'protester_id_type_locals_residents': 0,
    'protester_id_type_pensioners_retirees': 0,
    'protester_id_type_political_group': 0,
    'protester_id_type_prisoners': 0,
    'protester_id_type_protestors_generic': 0,
    'protester_id_type_religious_group': 0,
    'protester_id_type_soldiers_veterans': 0,
    'protester_id_type_students_youth':1,
    'protester_id_type_victims_families': 0,
    'protester_id_type_women':0,
    'protester_id_type_workers_unions': 0,
    'labor_wage_dispute': 0,
    'land_farm_issue': 0,
    'police_brutality':0,
    'political_behavior_process': 1,   # This seems to match gun control legislation the best
    'price increases_tax_policy': 0,
    'removal_of_politician':0,
    'social_restrictions':0
}
        
#append row to the dataframe
#X = X.append(new_protest, ignore_index=True)
X.loc["2018 March For Our Lives"] = new_protest
X

protestnumber  protesterviolence   pop_total  \
1999 Seattle WTO Protest            1.0                1.0  278548.148   
2018 March For Our Lives            4.0                0.0  327096.263   

                          pop_density  prosperity_2020  region_Africa  \
1999 Seattle WTO Protest        30.45             77.5            0.0   
2018 March For Our Lives        35.76             77.5            0.0   

                          region_Asia  region_Central America  region_Europe  \
1999 Seattle WTO Protest          0.0                     0.0            0.0   
2018 March For Our Lives          0.0                     0.0            0.0   

                          region_MENA  ...  \
1999 Seattle WTO Protest          0.0  ...   
2018 March For Our Lives          0.0  ...   

                          protester_id_type_victims_families  \
1999 Seattle WTO Protest                                 0.0   
2018 March For Our Lives                                 0.0   

                          protester_id_type_women  \
1999 Seattle WTO Protest                      0.0   
2018 March For Our Lives                      0.0   

                          protester_id_type_workers_unions  \
1999 Seattle WTO Protest                               1.0   
2018 March For Our Lives                               0.0   

                          labor_wage_dispute  land_farm_issue  \
1999 Seattle WTO Protest                 1.0              0.0   
2018 March For Our Lives                 0.0              0.0   

                          police_brutality  political_behavior_process  \
1999 Seattle WTO Protest               0.0                         1.0   
2018 March For Our Lives               0.0                         1.0   

                          price increases_tax_policy  removal_of_politician  \
1999 Seattle WTO Protest                         1.0                    0.0   
2018 March For Our Lives                         0.0                    0.0   

                          social_restrictions  
1999 Seattle WTO Protest                  1.0  
2018 March For Our Lives                  0.0  

[2 rows x 40 columns]

### Create protest for [Jan 6 storming of the U.S. Capitol](https://en.wikipedia.org/wiki/2021_storming_of_the_United_States_Capitol) in Washington D.C.

In [272]:
# 2021 D.C. Jan 6

# Create a dictionary that contains a value for each of the 40 input features

new_protest = {
    'protestnumber': 1,  # First protest of the year
    'protesterviolence': 1,
    'pop_total': 332915.074,  # Taken from WPP2019_TotalPopulationBySex.csv
    'pop_density':36.40,
    'prosperity_2020': 77.5,  # Taken from Legatum_Prosperity_Index_Full_2020_Data_Set Excel file - Score from 2007
    'region_Africa': 0,
    'region_Asia': 0,
    'region_Central America': 0,
    'region_Europe': 0,
    'region_MENA': 0,
    'region_North America': 1,
    'region_Oceania': 0,
    'region_South America': 0,
    'protest_size_category_1,000-4,999': 1,  #Protest size in the thousands
    'protest_size_category_10,000-100,000': 0,   
    'protest_size_category_100-999': 0,
    'protest_size_category_5,000-9,999': 0,
    'protest_size_category_50-99':0 ,
    'protest_size_category_Less than 50': 0,
    'protest_size_category_Over 100,000': 0,
    'protester_id_type_civil_human_rights': 0,
    'protester_id_type_ethnic_group': 0,
    'protester_id_type_locals_residents': 0,
    'protester_id_type_pensioners_retirees': 0,
    'protester_id_type_political_group': 1,
    'protester_id_type_prisoners': 0,
    'protester_id_type_protestors_generic': 0,
    'protester_id_type_religious_group': 0,
    'protester_id_type_soldiers_veterans': 0,
    'protester_id_type_students_youth':0,
    'protester_id_type_victims_families': 0,
    'protester_id_type_women':0,
    'protester_id_type_workers_unions': 0,
    'labor_wage_dispute': 0,
    'land_farm_issue': 0,
    'police_brutality':0,
    'political_behavior_process': 1,
    'price increases_tax_policy': 0,
    'removal_of_politician':1,
    'social_restrictions':0
}

X.loc["2021 D.C. Riot"] = new_protest
X


protestnumber  protesterviolence   pop_total  \
1999 Seattle WTO Protest            1.0                1.0  278548.148   
2018 March For Our Lives            4.0                0.0  327096.263   
2021 D.C. Riot                      1.0                1.0  332915.074   

                          pop_density  prosperity_2020  region_Africa  \
1999 Seattle WTO Protest        30.45             77.5            0.0   
2018 March For Our Lives        35.76             77.5            0.0   
2021 D.C. Riot                  36.40             77.5            0.0   

                          region_Asia  region_Central America  region_Europe  \
1999 Seattle WTO Protest          0.0                     0.0            0.0   
2018 March For Our Lives          0.0                     0.0            0.0   
2021 D.C. Riot                    0.0                     0.0            0.0   

                          region_MENA  ...  \
1999 Seattle WTO Protest          0.0  ...   
2018 March For Our Lives          0.0  ...   
2021 D.C. Riot                    0.0  ...   

                          protester_id_type_victims_families  \
1999 Seattle WTO Protest                                 0.0   
2018 March For Our Lives                                 0.0   
2021 D.C. Riot                                           0.0   

                          protester_id_type_women  \
1999 Seattle WTO Protest                      0.0   
2018 March For Our Lives                      0.0   
2021 D.C. Riot                                0.0   

                          protester_id_type_workers_unions  \
1999 Seattle WTO Protest                               1.0   
2018 March For Our Lives                               0.0   
2021 D.C. Riot                                         0.0   

                          labor_wage_dispute  land_farm_issue  \
1999 Seattle WTO Protest                 1.0              0.0   
2018 March For Our Lives                 0.0              0.0   
2021 D.C. Riot                           0.0              0.0   

                          police_brutality  political_behavior_process  \
1999 Seattle WTO Protest               0.0                         1.0   
2018 March For Our Lives               0.0                         1.0   
2021 D.C. Riot                         0.0                         1.0   

                          price increases_tax_policy  removal_of_politician  \
1999 Seattle WTO Protest                         1.0                    0.0   
2018 March For Our Lives                         0.0                    0.0   
2021 D.C. Riot                                   0.0                    1.0   

                          social_restrictions  
1999 Seattle WTO Protest                  1.0  
2018 March For Our Lives                  0.0  
2021 D.C. Riot                            0.0  

[3 rows x 40 columns]

Create dataframe to contain prediction results

In [278]:
pred_values = loaded_model.predict(X)

predictions_df = pd.DataFrame(pred_values, columns=['arrests', 'accomodation', 'beatings',
       'crowddispersal', 'ignore', 'killings', 'shootings'], index=X.index)

predictions_df

arrests  accomodation  beatings  crowddispersal  \
1999 Seattle WTO Protest        0             0         0               0   
2018 March For Our Lives        0             0         0               0   
2021 D.C. Riot                  0             0         0               0   

                          ignore  killings  shootings  
1999 Seattle WTO Protest       0         0          0  
2018 March For Our Lives       1         0          0  
2021 D.C. Riot                 0         0          0

In [274]:
# load the model from disk
model_file_2 = '../models/02_multi_label_logistic.pickle'
loaded_model_2 = pickle.load(open(model_file, 'rb'))



In [275]:
loaded_model_2

MultiOutputClassifier(estimator=RandomForestClassifier(max_depth=30,
                                                       max_leaf_nodes=100,
                                                       min_impurity_decrease=0,
                                                       min_samples_leaf=5,
                                                       min_samples_split=4,
                                                       n_estimators=50))